title: LTEC 5220
description: >
  Multimedia in Technology Applications
permalink: /training/:title/
baseurl: ""
url: "https://LTEC5220.ray.pillers.us"
site-twitter: #if your site has a twitter account, enter it here

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

# Author Settings
author: Raymond Piller
author-img: //static.vertigion.com/images/Avatar-Negative.png
about-author: >
  <b>LTEC 5220</b><br />
  <i>Windows Server Administration</i><br />
  <i>Cross-Training Job Aid</i>
  
  <ul class="menu">
    <li><a href="/training/intro">🔹 Start Training!</a></li>
  </ul>
  <hr />
  <ul class="menu">
    <li><a href="/about">🔸 About</a></li>
    <li><a href="/contact">🔸 Contact Us</a></li>
  </ul>
social-twitter: VertigoRay
social-facebook: VertigoRay
social-github: VertigoRay
social-linkedin: VertigoRay
social-blog: 'http://blog.vertigion.com'
social-email: Raymond.Piller@my.unt.edu

# Disqus
discus-identifier: vertigoray

# Tracker
analytics: UA-20345769-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-gist

paginate: 20
paginate_path: "/page/:num"

# gist:
#   noscript: false

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
